# Generated by Django 5.2 on 2025-04-14 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Identity",
            fields=[
                ("name", models.CharField(max_length=64)),
                (
                    "security_card_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dynamic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_time", models.DateTimeField()),
                ("login_position", models.CharField(max_length=64)),
                ("device_ip", models.CharField(max_length=128)),
                ("cpu_id", models.CharField(max_length=256)),
                ("disk_id", models.CharField(max_length=256)),
                ("auth_type", models.IntegerField(default=0)),
                ("device_type", models.IntegerField(default=0)),
                (
                    "security_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluate.identity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Direct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cert_dn", models.CharField(max_length=256)),
                ("cert_sn", models.CharField(max_length=256)),
                ("soft_type", models.IntegerField(default=0)),
                ("setup_type", models.IntegerField(default=0)),
                ("os_type", models.IntegerField(default=0)),
                ("firewall_status", models.BooleanField()),
                (
                    "security_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluate.identity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Unauthorized",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("times", models.IntegerField(default=0)),
                ("score", models.IntegerField(default=0)),
                ("position", models.CharField(max_length=128)),
                ("department", models.CharField(max_length=64)),
                ("api_id", models.CharField(max_length=64)),
                ("api_type", models.CharField(max_length=64)),
                ("data_level", models.IntegerField(default=0)),
                (
                    "security_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluate.identity",
                    ),
                ),
            ],
        ),
    ]
