# Generated by Django 5.2 on 2025-04-24 07:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Biometric",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("auth_type", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "biometric",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("login_time", models.CharField(max_length=64)),
                ("device_position", models.CharField(max_length=64)),
                ("device_ip", models.CharField(max_length=128)),
                ("cpu_id", models.CharField(max_length=256)),
                ("disk_id", models.CharField(max_length=256)),
                ("device_type", models.IntegerField(default=0)),
                ("cert", models.TextField(default="")),
            ],
            options={
                "db_table": "device",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("result", models.IntegerField()),
            ],
            options={
                "db_table": "permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Software",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("os_type", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "software",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
                ("security_card_id", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "realuser",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("security_card_id", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=64)),
                ("device_ip", models.CharField(max_length=64)),
                ("device_site", models.CharField(max_length=64)),
                ("login_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("cpu_id", models.CharField(default="", max_length=256)),
                ("disk_id", models.CharField(default="", max_length=256)),
                ("auth_type", models.IntegerField(default=0)),
                ("device_type", models.IntegerField(default=0)),
                ("cert", models.TextField(default="")),
                ("os_type", models.IntegerField(default=0)),
                ("oa_result", models.IntegerField(default=0)),
                ("score", models.FloatField(default=0)),
            ],
            options={
                "db_table": "tb_data_total",
            },
        ),
    ]
