# Generated by Django 5.2 on 2025-05-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64)),
                ('device_ip', models.CharField(max_length=64)),
                ('device_site', models.CharField(max_length=64)),
                ('cpu_id', models.CharField(default='', max_length=256)),
                ('disk_id', models.CharField(default='', max_length=256)),
                ('key_type', models.IntegerField(default=0)),
                ('device_type', models.IntegerField(default=0)),
                ('cert', models.TextField()),
                ('device_result', models.IntegerField(db_column='auth_result', default=0)),
                ('score', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'tb_device_score',
            },
        ),
        migrations.AlterField(
            model_name='local',
            name='cert',
            field=models.TextField(),
        ),
    ]
