# Generated by Django 5.2 on 2025-04-14 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("evaluate", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Direct",
            new_name="Security",
        ),
    ]
