# Generated by Django 5.2 on 2025-05-15 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0002_devicescore_alter_local_cert'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicescore',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
