# Generated by Django 5.2 on 2025-04-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluate", "0002_rename_direct_security"),
    ]

    operations = [
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "tb_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("security_card_id", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=64)),
                ("device_ip", models.CharField(max_length=64)),
                ("device_site", models.CharField(max_length=64)),
                ("cert_dn", models.CharField(max_length=256)),
                ("cert_sn", models.CharField(max_length=256)),
                ("soft_type", models.IntegerField(default=0)),
                ("setup_type", models.IntegerField(default=0)),
                ("os_type", models.IntegerField(default=0)),
                ("oa_count", models.IntegerField(default=0)),
                ("oa_score", models.IntegerField(default=0)),
                ("api_id", models.CharField(max_length=64)),
                ("api_type", models.CharField(max_length=64)),
                ("department", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "tb_data_total",
            },
        ),
        migrations.CreateModel(
            name="TrustScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_id", models.CharField(max_length=128)),
                ("security_card_id", models.CharField(max_length=128)),
                ("data_level", models.IntegerField(default=0)),
                ("result_code", models.IntegerField()),
                ("score", models.FloatField(default=0)),
                ("create_time", models.DateTimeField()),
            ],
            options={
                "db_table": "tb_historical_trust_scores",
            },
        ),
        migrations.RemoveField(
            model_name="security",
            name="security_card",
        ),
        migrations.RemoveField(
            model_name="unauthorized",
            name="security_card",
        ),
        migrations.DeleteModel(
            name="Dynamic",
        ),
        migrations.DeleteModel(
            name="Security",
        ),
        migrations.DeleteModel(
            name="Identity",
        ),
        migrations.DeleteModel(
            name="Unauthorized",
        ),
    ]
