# Generated by Django 5.2 on 2025-05-19 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0003_devicescore_login_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicescore',
            name='cert',
        ),
    ]
