# Generated by Django 5.2 on 2025-04-18 02:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluate", "0003_local_trustscore_remove_security_security_card_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Api",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("api_id", models.CharField(max_length=64)),
                ("api_type", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "api",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Biometric",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("auth_type", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "biometric",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Data",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("data_level", models.IntegerField()),
            ],
            options={
                "db_table": "data",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("login_time", models.CharField(max_length=64)),
                ("device_position", models.CharField(max_length=64)),
                ("device_ip", models.CharField(max_length=128)),
                ("cpu_id", models.CharField(max_length=256)),
                ("disk_id", models.CharField(max_length=256)),
                ("device_type", models.IntegerField(default=0)),
                ("cert_dn", models.CharField(max_length=256)),
                ("cert_sn", models.CharField(max_length=256)),
            ],
            options={
                "db_table": "device",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Software",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("soft_type", models.IntegerField(default=0)),
                ("setup_type", models.IntegerField(default=0)),
                ("os_type", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "software",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
                ("security_card_id", models.CharField(max_length=128)),
                ("position", models.CharField(max_length=64)),
                ("department", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "realuser",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="local",
            name="auth_type",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="local",
            name="cpu_id",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="local",
            name="data_level",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="local",
            name="device_type",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="local",
            name="disk_id",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="local",
            name="login_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="trustscore",
            name="result_code",
            field=models.IntegerField(default=0),
        ),
    ]
