# Generated by Django 5.2 on 2025-04-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluate", "0004_api_biometric_data_device_software_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="local",
            name="cert_dn",
        ),
        migrations.RemoveField(
            model_name="local",
            name="cert_sn",
        ),
        migrations.RemoveField(
            model_name="local",
            name="setup_type",
        ),
        migrations.RemoveField(
            model_name="local",
            name="soft_type",
        ),
        migrations.AddField(
            model_name="local",
            name="cert",
            field=models.CharField(default="", max_length=256),
        ),
    ]
