# Generated by Django 5.2 on 2025-04-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluate", "0007_remove_trustscore_result_local_oa_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="local",
            name="cert",
            field=models.TextField(default=""),
        ),
    ]
